# Importing libraries

In [1]:
import numpy as np
import pandas as pd

# Access CSV File

In [2]:
subs_df = pd.read_csv('../data/subscriptions.csv')

subs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customerSubscrCode  3 non-null      int64
 1   customerSubscrStat  3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [3]:
subs_df

   customerSubscrCode customerSubscrStat
0                   1             Member
1                   2               Gold
2                   3           Platinum

# Access JSON file

In [4]:
review_df = pd.read_json('../data/reviews.json')

review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   reviews  782 non-null    object
dtypes: object(1)
memory usage: 6.2+ KB

In [5]:
review_df.head()

                                             reviews
0  {'reviewId': 765, 'Review_Text': 'If you are a...
1  {'reviewId': 767, 'Review_Text': 'I met my fri...
2  {'reviewId': 768, 'Review_Text': 'I bought the...
3  {'reviewId': 769, 'Review_Text': 'Great fit. i...
4  {'reviewId': 770, 'Review_Text': 'Precious tee...

## How to clean a json file

In [6]:
reviews_df = pd.DataFrame.from_records(review_df['reviews'])
reviews_df.head()

,reviewId,Review_Text,Title
0,765,If you are afraid of the jumpsuit trend but li...,"Cute,looks like a dress on"
1,767,I met my friend at the mall today. she compli...,Don't like wearing dresses? try this.
2,768,I bought these assuming they would be the same...,All-in-all nice denim
3,769,Great fit. i love the slightly cropped leg and...,
4,770,"Precious tee, washes well, runs large",Nostalgia tee

# Access a SAS data set

In [7]:
eval_df = pd.read_sas('../data/techsupportevals.sas7bdat')

eval_df.info()

customers_df = pd.read_sas('../snowflake/customers.sas7bdat')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               5000 non-null   float64
 1   techSupportEval  4730 non-null   float64
dtypes: float64(2)
memory usage: 78.3 KB

In [8]:
eval_df

            ID  techSupportEval
0       9155.0              3.0
1       9160.0              3.0
2       9163.0              2.0
3       9170.0              2.0
4       9175.0              2.0
...        ...              ...
4995  174472.0              5.0
4996  174490.0              5.0
4997  174493.0              4.0
4998  174529.0              5.0
4999  174530.0              5.0

[5000 rows x 2 columns]

## Reading and Accessing Parquet files

In [9]:
gcs_key = '../keys'

customer_churn_df = pd.read_parquet('../gcs/customer_churn_data.parquet')

# JOINING DATA

In [10]:
df = pd.merge(customer_churn_df, customers_df, on = "custId", how = 'inner').drop(columns = 'custId')

In [11]:
df = df.merge(subs_df, on = "customerSubscrCode", how = 'inner').drop(columns = 'customerSubscrCode')

In [12]:
df = df.merge(eval_df, on = "ID", how = 'inner')

In [13]:
df = df.merge(reviews_df, on = "reviewId", how = 'left').drop(columns = 'reviewId')

In [14]:
df.columns

Index(['ID', 'LostCustomer', 'regionPctCustomers', 'numOfTotalReturns',
       'wksSinceLastPurch', 'basktPurchCount12Month', 'LastPurchaseAmount',
       'AvgPurchaseAmount12', 'AvgPurchaseAmountTotal', 'intAdExposureCount12',
       'intAdExposureCount36', 'intAdExposureCountAll', 'socialMediaAdCount12',
       'socialMediaAdCount36', 'socialMediaAdCountAll',
       'totalNumProdPurchased', 'custInitiatedContacts', 'avgDiscountValue12',
       'customersales', 'wksSinceFirstPurch', 'DemHomeOwnerCode',
       'customerGender', 'EstimatedIncome', 'regionMedHomeVal', 'birthDate',
       'customerSubscrStat', 'techSupportEval', 'Review_Text', 'Title'],
      dtype='object')

In [15]:
df.head()

,ID,LostCustomer,regionPctCustomers,numOfTotalReturns,wksSinceLastPurch,basktPurchCount12Month,LastPurchaseAmount,AvgPurchaseAmount12,AvgPurchaseAmountTotal,intAdExposureCount12,...,wksSinceFirstPurch,DemHomeOwnerCode,customerGender,EstimatedIncome,regionMedHomeVal,birthDate,customerSubscrStat,techSupportEval,Review_Text,Title
0,9155.0,0.0,43.0,0.0,14.0,10.0,50.0,0.0,55.65,27.0,...,89.0,b'U',b'F',93000.0,59280.0,2004-11-13,Platinum,3.0,NaN,NaN
1,9160.0,0.0,19.0,1.0,19.0,3.0,50.0,62.5,61.90,13.0,...,89.0,b'H',b'M',84000.0,170820.0,1974-03-14,Platinum,3.0,NaN,NaN
2,9163.0,0.0,19.0,0.0,7.0,10.0,50.0,0.0,35.20,32.0,...,148.0,b'H',b'F',140000.0,92430.0,2006-02-22,Platinum,2.0,NaN,NaN
3,9170.0,0.0,33.0,5.0,7.0,2.0,50.0,40.0,34.75,31.0,...,93.0,b'U',b'F',142000.0,53430.0,2006-04-19,Platinum,2.0,NaN,NaN
4,9175.0,0.0,22.0,0.0,6.0,10.0,50.0,0.0,62.95,40.0,...,137.0,b'H',b'F',83000.0,443690.0,2002-02-23,Platinum,2.0,NaN,NaN

In [16]:
df['DemHomeOwnerCode'] = df['DemHomeOwnerCode'].str.decode('utf-8')
df['customerGender'] = df['customerGender'].str.decode('utf-8')

In [17]:
df['demHomeOwner'] = df['DemHomeOwnerCode'].map({"U": 'Unknown', "H":'HomeOwner'})

df.drop(columns="DemHomeOwnerCode", inplace = True)

In [25]:
df.head()

,ID,LostCustomer,regionPctCustomers,numOfTotalReturns,wksSinceLastPurch,basktPurchCount12Month,LastPurchaseAmount,AvgPurchaseAmount12,AvgPurchaseAmountTotal,intAdExposureCount12,...,wksSinceFirstPurch,customerGender,EstimatedIncome,regionMedHomeVal,customerSubscrStat,techSupportEval,Review_Text,Title,demHomeOwner,customerAge
0,9155.0,0.0,43.0,0.0,14.0,10.0,50.0,0.0,55.65,27.0,...,89.0,F,93000.0,59280.0,Platinum,3.0,NaN,NaN,Unknown,21.0
1,9160.0,0.0,19.0,1.0,19.0,3.0,50.0,62.5,61.90,13.0,...,89.0,M,84000.0,170820.0,Platinum,3.0,NaN,NaN,HomeOwner,52.0
2,9163.0,0.0,19.0,0.0,7.0,10.0,50.0,0.0,35.20,32.0,...,148.0,F,140000.0,92430.0,Platinum,2.0,NaN,NaN,HomeOwner,20.0
3,9170.0,0.0,33.0,5.0,7.0,2.0,50.0,40.0,34.75,31.0,...,93.0,F,142000.0,53430.0,Platinum,2.0,NaN,NaN,Unknown,20.0
4,9175.0,0.0,22.0,0.0,6.0,10.0,50.0,0.0,62.95,40.0,...,137.0,F,83000.0,443690.0,Platinum,2.0,NaN,NaN,HomeOwner,24.0

In [20]:
df['demHomeOwner'].value_counts()

demHomeOwner
HomeOwner    2756
Unknown      2244
Name: count, dtype: int64

In [21]:
df['customerAge'] = ((pd.Timestamp.now() - pd.to_datetime(df['birthDate'])).dt.days/365.25)

In [22]:
df['customerAge'] =df['customerAge'].apply(lambda x: int(x) if pd.notnull(x) else np.nan)

In [24]:
df.drop(columns='birthDate', inplace = True)

In [28]:
df['AvgPurchasePerAd'] = df['AvgPurchaseAmount12']/df['intAdExposureCount12']

In [29]:
df.to_csv('../data/customer_churn.csv')